# SSTI detection — model evaluation

In [1]:
"""
Reusable classical-ML modeling pipeline.
========================================

Design goal: point this at ANY tabular dataset with a label column and get
a fair, reproducible comparison of 7 classifiers. Works for binary problems and multiclass problems .

Pipeline shape (always the same order, because order is what protects against data leakage):

    load_data  ->  split_data  ->  scale_features  ->  train  ->  evaluate

Why the order matters:
  - Split BEFORE scaling. The scaler is fitted on training data only, then
    reused to transform the test set. Fitting on the full dataset would leak
    test-set statistics (mean/std) into training — a classic reviewer catch.
  - Stratify the split so rare attack classes appear in both train and test
    at the same ratio as in the full dataset.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import (
    train_test_split, RandomizedSearchCV, StratifiedKFold
)
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    classification_report, confusion_matrix, roc_auc_score, f1_score
)

from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

import warnings
warnings.filterwarnings('ignore')


# ======================================================================
# GLOBAL CONFIG 
# ======================================================================


RANDOM_STATE = 42     # one seed everywhere (split, CV, every model)
TEST_SIZE    = 0.2    # 80/20 train/test split

# Shared CV strategy for every tuned model. StratifiedKFold keeps class proportions identical 
# in each fold — critical when some attack classes are rare. 3 folds instead of 5 because the
# datasets are large and 5 folds nearly doubles tuning time for little gain.
cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)

## Data loading and preprocessing

In [2]:
# Load Data 
# FEATURE_VERSION picks the feature set for the WHOLE notebook (updated 2026-10-06).
#   'v1' -> train_features.csv    : the original 17 features
#   'v2' -> train_features_v2.csv : 18 features, see Dataset/scripts/ssti_feature_extraction_v2.py
# Same rows, same order, same base_id and label in both -- only feature columns differ.
# Every later cell (random split, threshold selection, grouped evaluation) reads
# FEATURES_FILE, so this one line is the only thing to change.
FEATURE_VERSION = 'v2'
FEATURES_FILE = {'v1': 'train_features.csv', 'v2': 'train_features_v2.csv'}[FEATURE_VERSION]
df = pd.read_csv(FEATURES_FILE)

# Drop Payload Column
df.drop(columns=['payload',], inplace=True)
df.head()

,base_id,payload_length,special_char_ratio,count_double_brace,count_dollar_brace,count_hash_brace,delimiter_family_count,max_bracket_depth,has_dunder_chain,has_exec_tokens,has_java_reflection,has_flask_objects,has_string_operation,count_method_calls,count_dots,v2_count_erb_open,v2_has_arithmetic_probe,v2_call_inside_delim,v2_max_attr_chain_len,label
0,<%=N*N%>,10,0.600000,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,1
1,<%=N*'S'%>,12,0.666667,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,1
2,"<%=""S""%>",12,0.583333,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1
3,"<%=system(""S"")%>",19,0.473684,0,0,0,1,1,0,1,0,0,0,0,0,1,0,0,0,1
4,"<%=exec(""S"")%>",17,0.529412,0,0,0,1,1,0,1,0,0,0,0,0,1,0,0,0,1

In [3]:
#  SPLIT INTO INPUTS (X) AND ANSWER (y)
X = df.drop(columns=['label', 'base_id'])
Y = df.label

# Split Train and Test Data
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state = 15)

scaler = StandardScaler()
x_train["payload_length"] = scaler.fit_transform(x_train[["payload_length"]])
x_test["payload_length"]  = scaler.transform(x_test[["payload_length"]])
# print(x_train[["payload_length"]].head())

## Modeling and evaluation

In [4]:


# ======================================================================
# STEP 2 — TRAINING FUNCTIONS (one per model, training ONLY)
# ======================================================================
# Each function does exactly one thing: return a fitted model.

# --- Simple baselines: no tuning needed ------------------------------

def train_naive_bayes(X_train, y_train):
    # GaussianNB has essentially nothing worth tuning. It assumes feature
    # independence, which is false for both network traffic and payload
    # features, so expect it to be the weakest model — its job is to be
    # the floor the other models must beat.
    model = GaussianNB()
    model.fit(X_train, y_train)
    return model


def train_logistic_regression(X_train, y_train):
    # class_weight="balanced" makes mistakes on rare classes cost more,
    # so the model can't win by always predicting the majority class.
    # max_iter raised so the optimizer converges on scaled features.
    model = LogisticRegression(
        max_iter=1000, class_weight="balanced", n_jobs=-1
    )
    model.fit(X_train, y_train)
    return model


# ------------------------------------- Light tuning ------------------------------------- 

def train_decision_tree(X_train, y_train):
    # The params dict is the experiment: these are the knobs being searched.
    params = {
        "max_depth": [None, 10, 20, 40],   # how deep the tree may grow
        "min_samples_leaf": [1, 5, 20],    # bigger leaves = less overfitting
        "criterion": ["gini", "entropy"],  # how splits are scored
    }
    search = RandomizedSearchCV(
        DecisionTreeClassifier(class_weight="balanced",
                               random_state=RANDOM_STATE),
        params,
        n_iter=8,
        scoring="f1_macro",   # macro-F1, not accuracy, so rare classes
                              # count equally — the honest metric for
                              # imbalanced security data
        cv=cv, n_jobs=-1, random_state=RANDOM_STATE
    )
    search.fit(X_train, y_train)
    print("  best params:", search.best_params_)
    return search.best_estimator_


# ------------------------------------- Slow models -----------------------------------------------
# NOTE: on very large datasets (CICIDS2017 full), tune these on a stratified subsample first,
# then refit the best params on all data On the SSTI dataset (~hundreds of rows) they run fine as-is.

def train_svm(X_train, y_train):
    params = {
        "C": [0.1, 1, 10],              # regularization strength
        "gamma": ["scale", 0.01, 0.1],  # reach of one sample's influence
    }
    search = RandomizedSearchCV(
        # probability=True is slower but required: without it SVM can't
        # output probabilities and ROC-AUC (our headline metric) fails.
        SVC(kernel="rbf", probability=True,
            class_weight="balanced", random_state=RANDOM_STATE),
        params, n_iter=6, scoring="f1_macro", cv=cv,
        n_jobs=-1, random_state=RANDOM_STATE
    )
    search.fit(X_train, y_train)
    print("  best params:", search.best_params_)
    return search.best_estimator_


def train_knn(X_train, y_train):
    params = {
        "n_neighbors": [3, 5, 11, 21],       # how many neighbors vote
        "weights": ["uniform", "distance"],  # equal vote vs closer = louder
    }
    search = RandomizedSearchCV(
        KNeighborsClassifier(n_jobs=-1),
        params, n_iter=6, scoring="f1_macro", cv=cv,
        n_jobs=-1, random_state=RANDOM_STATE
    )
    search.fit(X_train, y_train)
    print("  best params:", search.best_params_)
    return search.best_estimator_


# --- Models that genuinely benefit from tuning ------------------------

def train_random_forest(X_train, y_train):
    params = {
        "n_estimators": [200, 400, 600],   # number of trees
        "max_depth": [None, 20, 40],       # depth of each tree
        "min_samples_leaf": [1, 2, 5],     # overfitting control
        "max_features": ["sqrt", "log2"],  # features considered per split
    }
    search = RandomizedSearchCV(
        # "balanced_subsample" recomputes class weights per bootstrap
        # sample — the RF-appropriate version of "balanced".
        RandomForestClassifier(class_weight="balanced_subsample",
                               random_state=RANDOM_STATE, n_jobs=-1),
        params, n_iter=10, scoring="f1_macro", cv=cv,
        n_jobs=-1, random_state=RANDOM_STATE
    )
    search.fit(X_train, y_train)
    print("  best params:", search.best_params_)
    return search.best_estimator_


def train_xgboost(X_train, y_train):
    params = {
        "n_estimators": [300, 500, 800],    # boosting rounds
        "max_depth": [4, 6, 8],             # tree depth
        "learning_rate": [0.03, 0.1, 0.2],  # step size per round
        "subsample": [0.8, 1.0],            # row sampling per tree
        "colsample_bytree": [0.8, 1.0],     # feature sampling per tree
    }

    
    n_classes = len(np.unique(y_train))
    metric = "logloss" if n_classes == 2 else "mlogloss" # here we choose ("logloss") for the binary problem and("mlogloss") for the multiclass problem

    search = RandomizedSearchCV(
        # tree_method="hist" = fast histogram algorithm, matters at
        # CICIDS2017 scale.
        XGBClassifier(tree_method="hist", eval_metric=metric,
                      n_jobs=-1, random_state=RANDOM_STATE),
        params, n_iter=12, scoring="f1_macro", cv=cv,             # training — hyperparameters are chosen by scoring="f1_macro" below. 
        n_jobs=-1, random_state=RANDOM_STATE
    )
    search.fit(X_train, y_train)
    print("  best params:", search.best_params_)
    return search.best_estimator_


# ======================================================================
# STEP 3 — EVALUATION (one function, every model, same rules)
# ======================================================================

def evaluate_model(name, model, X_test, y_test, class_names=None):
    """
    Evaluate one fitted model and return its metrics as a dict.

    Handles binary AND multiclass automatically:
      - Binary: roc_auc_score wants ONLY the positive-class probability, i.e. y_prob[:, 1].
      - Multiclass : it wants the full probability matrix plus multi_class='ovr'.
    Getting this wrong is a silent bug — sklearn raises an error in one
    direction but in the other it can compute a misleading number.

    Returns the metrics (instead of only printing) so a comparison table
    can be built across models — that table becomes the results section of the paper.
    """
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)

    print(f"\n{'='*50}")
    print(f"  {name}")
    print(f"{'='*50}")
    print(classification_report(y_test, y_pred, target_names=class_names))

    n_classes = len(np.unique(y_test))
    if n_classes == 2:
        auc = roc_auc_score(y_test, y_prob[:, 1])
    else:
        auc = roc_auc_score(y_test, y_prob,
                            multi_class="ovr", average="macro")
    print(f"ROC-AUC: {auc:.4f}")

    # Confusion matrix heatmap — labeled with real class names when known.
    ticks = class_names if class_names is not None else "auto"
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=ticks, yticklabels=ticks)
    plt.title(f"Confusion matrix — {name}")
    plt.xlabel("Predicted"); plt.ylabel("Actual")
    plt.tight_layout(); plt.show()

    return {
        "model": name,
        "roc_auc": auc,
        "f1_macro": f1_score(y_test, y_pred, average="macro"),
    }

In [5]:
class_names = ['BENIGN', 'SSTI_Vulnerable']

# Train each model. Each function returns a fitted, ready-to-use model.
models = {
    "Naive Bayes":         train_naive_bayes(x_train, y_train),
    "Logistic Regression": train_logistic_regression(x_train, y_train),
    "KNN":                 train_knn(x_train, y_train),
    "SVM":                 train_svm(x_train, y_train),
    "Decision Tree":       train_decision_tree(x_train, y_train),
    "Random Forest":       train_random_forest(x_train, y_train),
    "XGBoost":             train_xgboost(x_train, y_train),
}

# Evaluate each trained model with the same function, so the comparison is fair.
for name, mdl in models.items():
    evaluate_model(name, mdl, x_test, y_test)

  best params: {'weights': 'distance', 'n_neighbors': 3}

  best params: {'gamma': 0.1, 'C': 10}

  best params: {'min_samples_leaf': 1, 'max_depth': None, 'criterion': 'gini'}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}

  best params: {'subsample': 0.8, 'n_estimators': 800, 'max_depth': 4, 'learning_rate': 0.03, 'colsample_bytree': 0.8}

==================================================
  Naive Bayes
==================================================
              precision    recall  f1-score   support

           0       0.73      0.98      0.83       389
           1       0.97      0.63      0.77       393

    accuracy                           0.81       782
   macro avg       0.85      0.81      0.80       782
weighted avg       0.85      0.81      0.80       782

ROC-AUC: 0.9315

==================================================
  Logistic Regression
==================================================
              precision    recall  f1-score   support

           0       0.85      0.91      0.88       389
           1       0.91      0.84      0.87       393

    accuracy                           0.88       782
   macro avg       0.88      0.88      0.88       782
weighted avg       0.88      0.88      0.88       782

ROC-AUC: 0.9582

==================================================
  KNN
==================================================
              precision    recall  f1-score   support

           0       0.91      0.94      0.92       389
           1       0.93      0.91      0.92       393

    accuracy                           0.92       782
   macro avg       0.92      0.92      0.92       782
weighted avg       0.92      0.92      0.92       782

ROC-AUC: 0.9522

==================================================
  SVM
==================================================
              precision    recall  f1-score   support

           0       0.91      0.94      0.92       389
           1       0.94      0.90      0.92       393

    accuracy                           0.92       782
   macro avg       0.92      0.92      0.92       782
weighted avg       0.92      0.92      0.92       782

ROC-AUC: 0.9753

==================================================
  Decision Tree
==================================================
              precision    recall  f1-score   support

           0       0.91      0.91      0.91       389
           1       0.91      0.91      0.91       393

    accuracy                           0.91       782
   macro avg       0.91      0.91      0.91       782
weighted avg       0.91      0.91      0.91       782

ROC-AUC: 0.9179

==================================================
  Random Forest
==================================================
              precision    recall  f1-score   support

           0       0.93      0.92      0.92       389
           1       0.92      0.93      0.93       393

    accuracy                           0.92       782
   macro avg       0.92      0.92      0.92       782
weighted avg       0.92      0.92      0.92       782

ROC-AUC: 0.9780

==================================================
  XGBoost
==================================================
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       389
           1       0.93      0.93      0.93       393

    accuracy                           0.93       782
   macro avg       0.93      0.93      0.93       782
weighted avg       0.93      0.93      0.93       782

ROC-AUC: 0.9796

## Threshold selection

Every model outputs a probability, and `predict()` flags an input as an attack when that probability is at least 0.5. Nothing makes 0.5 the right cutoff. This step chooses the cutoff from the **training data only**, then applies it once to the test set from cell 5 and to the external test set. Choosing it on a test set would make that test result a cherry-pick instead of a measurement.

It uses the same random split as cells 1–8 (no grouping), and reports two rules side by side:

- **best F1:** the cutoff with the best balance of precision and recall on the training data.
- **5% false alarms:** the cutoff that flags at most 5% of benign training rows. Use this one for the external set: about 49% of the training rows are attacks but only about 9% of the external rows are, and a best-F1 cutoff does not carry over when that share changes, while a false-alarm rate is measured on benign rows alone.

In [6]:
# ======================================================================
# STEP 5 — THRESHOLD SELECTION (same random split as cells 1-8)
# ======================================================================
from sklearn.base import clone
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import precision_score, recall_score, precision_recall_curve


def out_of_fold_scores(model, X_train, y_train, cv=cv):
    # Attack probability for every TRAINING row, each scored by a copy of the
    # model that did not train on that row (the same `cv` folds as cell 2).
    # clone() keeps the tuned settings but drops what was learned, so no row
    # is scored by a model that has already seen it.
    return cross_val_predict(clone(model), X_train, y_train, cv=cv,
                             method="predict_proba")[:, 1]


def best_f1_threshold(y_true, scores):
    # Try every possible cutoff and keep the one with the highest F1.
    precision, recall, thresholds = precision_recall_curve(y_true, scores)
    f1 = 2 * precision * recall / (precision + recall + 1e-12)
    return float(thresholds[np.argmax(f1[:-1])])


def false_alarm_threshold(y_true, scores, target_fpr=0.05):
    # The cutoff that only `target_fpr` of the benign rows score above.
    benign_scores = scores[np.asarray(y_true) == 0]
    return float(np.quantile(benign_scores, 1 - target_fpr))


def metrics_at(model, X, y, threshold):
    # Precision, recall, F1 and error counts when the cutoff is `threshold`.
    y_pred = (model.predict_proba(X)[:, 1] >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y, y_pred, labels=[0, 1]).ravel()
    return {
        "precision": precision_score(y, y_pred, zero_division=0),
        "recall": recall_score(y, y_pred),
        "f1": f1_score(y, y_pred),
        "false_alarms": int(fp),
        "missed_attacks": int(fn),
    }


def load_external(features_file, columns, scaler):
    # The external test set in the same feature version and column order as
    # training ('train_features_v2.csv' -> 'test_features_v2.csv'), scaled
    # with the TRAINING scaler.
    external = pd.read_csv(features_file.replace("train_", "test_"))
    x_external = external[columns].copy()
    x_external["payload_length"] = scaler.transform(x_external[["payload_length"]])
    return x_external, external["label"]


# Each rule turns training labels + out-of-fold scores into one cutoff.
# To try another rule later, write one function and add one line here.
THRESHOLD_RULES = {
    "best F1":         best_f1_threshold,
    "5% false alarms": false_alarm_threshold,
}

In [7]:
# Caveat: the folds are not grouped (same as cells 1-8), and each model's
# settings were tuned on all of x_train, so the training scores used here
# are slightly optimistic. Both make the chosen cutoffs a little too low.

x_external, y_external = load_external(FEATURES_FILE, x_train.columns, scaler)

threshold_rows = []
for name, model in models.items():
    scores = out_of_fold_scores(model, x_train, y_train)
    cutoffs = {"default 0.5": 0.5}
    for rule_name, rule in THRESHOLD_RULES.items():
        cutoffs[rule_name] = rule(y_train, scores)

    for cutoff_name, threshold in cutoffs.items():
        for set_name, X, y in [("test (cell 5)", x_test, y_test),
                               ("external", x_external, y_external)]:
            threshold_rows.append({"model": name, "set": set_name, "cutoff": cutoff_name,
                                   "threshold": threshold, **metrics_at(model, X, y, threshold)})

threshold_table = pd.DataFrame(threshold_rows).round(3)
threshold_table[threshold_table["set"] == "external"]

,model,set,cutoff,threshold,precision,recall,f1,false_alarms,missed_attacks
1,Naive Bayes,external,default 0.5,0.500,0.800,0.681,0.736,8,15
3,Naive Bayes,external,best F1,0.000,0.239,1.000,0.385,150,0
5,Naive Bayes,external,5% false alarms,0.000,0.650,0.830,0.729,21,8
7,Logistic Regression,external,default 0.5,0.500,0.495,0.957,0.652,46,2
9,Logistic Regression,external,best F1,0.410,0.426,0.979,0.594,62,1
11,Logistic Regression,external,5% false alarms,0.660,0.536,0.787,0.638,32,10
13,KNN,external,default 0.5,0.500,0.621,0.872,0.726,25,6
15,KNN,external,best F1,0.348,0.600,0.894,0.718,28,5
17,KNN,external,5% false alarms,0.688,0.678,0.851,0.755,19,7
19,SVM,external,default 0.5,0.500,0.618,0.894,0.730,26,5
21,SVM,external,best F1,0.609,0.667,0.894,0.764,21,5
23,SVM,external,5% false alarms,0.673,0.683,0.872,0.766,19,6
25,Decision Tree,external,default 0.5,0.500,0.568,0.894,0.694,32,5
27,Decision Tree,external,best F1,0.587,0.592,0.894,0.712,29,5
29,Decision Tree,external,5% false alarms,1.000,0.609,0.894,0.724,27,5
31,Random Forest,external,default 0.5,0.500,0.629,0.936,0.752,26,3
33,Random Forest,external,best F1,0.401,0.582,0.979,0.730,33,1
35,Random Forest,external,5% false alarms,0.644,0.683,0.915,0.782,20,4
37,XGBoost,external,default 0.5,0.500,0.662,0.957,0.783,23,2
39,XGBoost,external,best F1,0.526,0.662,0.957,0.783,23,2
41,XGBoost,external,5% false alarms,0.636,0.738,0.957,0.833,16,2

In [8]:
# Same table for the test set from cell 5.
threshold_table[threshold_table["set"] == "test (cell 5)"]

,model,set,cutoff,threshold,precision,recall,f1,false_alarms,missed_attacks
0,Naive Bayes,test (cell 5),default 0.5,0.500,0.973,0.634,0.767,7,144
2,Naive Bayes,test (cell 5),best F1,0.000,0.736,0.992,0.845,140,3
4,Naive Bayes,test (cell 5),5% false alarms,0.000,0.959,0.712,0.818,12,113
6,Logistic Regression,test (cell 5),default 0.5,0.500,0.907,0.840,0.872,34,63
8,Logistic Regression,test (cell 5),best F1,0.410,0.880,0.896,0.888,48,41
10,Logistic Regression,test (cell 5),5% false alarms,0.660,0.962,0.763,0.851,12,93
12,KNN,test (cell 5),default 0.5,0.500,0.933,0.919,0.926,26,32
14,KNN,test (cell 5),best F1,0.348,0.915,0.936,0.926,34,25
16,KNN,test (cell 5),5% false alarms,0.688,0.951,0.880,0.914,18,47
18,SVM,test (cell 5),default 0.5,0.500,0.925,0.916,0.921,29,33
20,SVM,test (cell 5),best F1,0.609,0.954,0.901,0.927,17,39
22,SVM,test (cell 5),5% false alarms,0.673,0.961,0.875,0.916,14,49
24,Decision Tree,test (cell 5),default 0.5,0.500,0.909,0.911,0.910,36,35
26,Decision Tree,test (cell 5),best F1,0.587,0.919,0.891,0.904,31,43
28,Decision Tree,test (cell 5),5% false alarms,1.000,0.926,0.888,0.906,28,44
30,Random Forest,test (cell 5),default 0.5,0.500,0.920,0.931,0.925,32,27
32,Random Forest,test (cell 5),best F1,0.401,0.902,0.934,0.918,40,26
34,Random Forest,test (cell 5),5% false alarms,0.644,0.948,0.883,0.914,19,46
36,XGBoost,test (cell 5),default 0.5,0.500,0.927,0.931,0.929,29,27
38,XGBoost,test (cell 5),best F1,0.526,0.928,0.924,0.926,28,30
40,XGBoost,test (cell 5),5% false alarms,0.636,0.948,0.885,0.916,19,45

## Grouped evaluation

Cells 1–8 split the rows at random, so two variants of the same payload can land on both sides of the split. For example, `{{7*7}}` and `{{8*9}}` share the skeleton (`base_id`) `{{N*N}}`. If one is in training and the other in testing, the model recognises the test payload instead of detecting it, and the score is inflated.

The steps below split by `base_id`: every payload skeleton is either all in training or all in testing. They also score the separate external test set, which was collected independently of the training data.

In [9]:
# ======================================================================
# STEP 6 — GROUPED SPLIT (no payload skeleton on both sides)
# ======================================================================
from sklearn.model_selection import GroupShuffleSplit, StratifiedGroupKFold
from sklearn.metrics import precision_score, recall_score
# load_external() is defined in STEP 5 (threshold selection).


def scale_payload_length(x_train, x_test):
    # Same rule as cell 5: only payload_length is scaled, and the scaler is
    # fitted on the training rows only, then reused on the test rows.
    x_train, x_test = x_train.copy(), x_test.copy()
    scaler = StandardScaler()
    x_train["payload_length"] = scaler.fit_transform(x_train[["payload_length"]])
    x_test["payload_length"] = scaler.transform(x_test[["payload_length"]])
    return x_train, x_test, scaler


def group_split(df, test_size=TEST_SIZE, seed=RANDOM_STATE):
    """Like train_test_split in cell 5, but grouped on base_id.

    test_size is a share of GROUPS, not of rows, so the test set is about
    (not exactly) 20% of the rows.
    """
    X = df.drop(columns=["label", "base_id"])
    y = df["label"]
    groups = df["base_id"]

    splitter = GroupShuffleSplit(n_splits=1, test_size=test_size, random_state=seed)
    train_idx, test_idx = next(splitter.split(X, y, groups))

    # The whole point of this function: no skeleton on both sides.
    assert not set(groups.iloc[train_idx]) & set(groups.iloc[test_idx])

    x_train, x_test, scaler = scale_payload_length(X.iloc[train_idx], X.iloc[test_idx])
    return x_train, x_test, y.iloc[train_idx], y.iloc[test_idx], scaler


def score_row(reading, name, model, X, y):
    # One row of the comparison table: the numbers that matter for a detector.
    # Precision = of the inputs flagged, how many were attacks.
    # Recall    = of the attacks, how many were flagged.
    y_pred = model.predict(X)
    tn, fp, fn, tp = confusion_matrix(y, y_pred, labels=[0, 1]).ravel()
    return {
        "reading": reading,
        "model": name,
        "precision": precision_score(y, y_pred, zero_division=0),
        "recall": recall_score(y, y_pred),
        "f1": f1_score(y, y_pred),
        "roc_auc": roc_auc_score(y, model.predict_proba(X)[:, 1]),
        "false_alarms": int(fp),
        "missed_attacks": int(fn),
    }

In [10]:
# ======================================================================
# STEP 7 — TRAIN ON THE GROUPED SPLIT, EVALUATE ON HOLDOUT AND EXTERNAL
# ======================================================================
# Same 7 training functions as cell 8, unchanged.
#
# Caveat: inside each training function, hyperparameters are tuned with the
# ungrouped `cv` from cell 2, so tuning can see variants of one payload. That
# can make the chosen settings slightly optimistic. The readings below are
# still clean: no holdout or external skeleton is ever seen in training.

SHOW_REPORTS = True   # False = skip the per-model reports and plots, keep the table

gx_train, gx_test, gy_train, gy_test, g_scaler = group_split(df)
gx_external, gy_external = load_external(FEATURES_FILE, gx_train.columns, g_scaler)
print(f"grouped split: {len(gx_train)} training rows, {len(gx_test)} holdout rows, "
      f"{len(gx_external)} external rows")

grouped_models = {
    "Naive Bayes":         train_naive_bayes(gx_train, gy_train),
    "Logistic Regression": train_logistic_regression(gx_train, gy_train),
    "KNN":                 train_knn(gx_train, gy_train),
    "SVM":                 train_svm(gx_train, gy_train),
    "Decision Tree":       train_decision_tree(gx_train, gy_train),
    "Random Forest":       train_random_forest(gx_train, gy_train),
    "XGBoost":             train_xgboost(gx_train, gy_train),
}

rows = []
for name, mdl in grouped_models.items():
    if SHOW_REPORTS:
        evaluate_model(f"{name} | grouped holdout", mdl, gx_test, gy_test, class_names)
        evaluate_model(f"{name} | external", mdl, gx_external, gy_external, class_names)
    rows.append(score_row("random split (cell 8)", name, models[name], x_test, y_test))
    rows.append(score_row("grouped holdout", name, mdl, gx_test, gy_test))
    rows.append(score_row("external", name, mdl, gx_external, gy_external))

comparison = pd.DataFrame(rows)

grouped split: 3191 training rows, 715 holdout rows, 547 external rows

  best params: {'weights': 'distance', 'n_neighbors': 3}

  best params: {'gamma': 0.1, 'C': 10}
  best params: {'min_samples_leaf': 1, 'max_depth': 20, 'criterion': 'entropy'}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}

  best params: {'subsample': 0.8, 'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.1, 'colsample_bytree': 0.8}

==================================================
  Naive Bayes | grouped holdout
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.72      0.95      0.82       331
SSTI_Vulnerable       0.94      0.68      0.79       384

       accuracy                           0.80       715
      macro avg       0.83      0.81      0.80       715
   weighted avg       0.84      0.80      0.80       715

ROC-AUC: 0.9088

==================================================
  Naive Bayes | external
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.98      0.97      0.97       500
SSTI_Vulnerable       0.69      0.74      0.71        47

       accuracy                           0.95       547
      macro avg       0.83      0.86      0.84       547
   weighted avg       0.95      0.95      0.95       547

ROC-AUC: 0.9663

==================================================
  Logistic Regression | grouped holdout
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.82      0.85      0.84       331
SSTI_Vulnerable       0.87      0.84      0.85       384

       accuracy                           0.84       715
      macro avg       0.84      0.85      0.84       715
   weighted avg       0.85      0.84      0.84       715

ROC-AUC: 0.9456

==================================================
  Logistic Regression | external
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.91      0.95       500
SSTI_Vulnerable       0.48      0.91      0.63        47

       accuracy                           0.91       547
      macro avg       0.73      0.91      0.79       547
   weighted avg       0.95      0.91      0.92       547

ROC-AUC: 0.9745

==================================================
  KNN | grouped holdout
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.88      0.87      0.87       331
SSTI_Vulnerable       0.89      0.90      0.89       384

       accuracy                           0.88       715
      macro avg       0.88      0.88      0.88       715
   weighted avg       0.88      0.88      0.88       715

ROC-AUC: 0.9158

==================================================
  KNN | external
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.94      0.97       500
SSTI_Vulnerable       0.59      0.89      0.71        47

       accuracy                           0.94       547
      macro avg       0.79      0.92      0.84       547
   weighted avg       0.96      0.94      0.94       547

ROC-AUC: 0.9564

==================================================
  SVM | grouped holdout
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.87      0.89      0.88       331
SSTI_Vulnerable       0.90      0.88      0.89       384

       accuracy                           0.89       715
      macro avg       0.88      0.89      0.88       715
   weighted avg       0.89      0.89      0.89       715

ROC-AUC: 0.9573

==================================================
  SVM | external
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.95      0.97       500
SSTI_Vulnerable       0.61      0.91      0.74        47

       accuracy                           0.94       547
      macro avg       0.80      0.93      0.85       547
   weighted avg       0.96      0.94      0.95       547

ROC-AUC: 0.9809

==================================================
  Decision Tree | grouped holdout
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.88      0.83      0.85       331
SSTI_Vulnerable       0.86      0.90      0.88       384

       accuracy                           0.87       715
      macro avg       0.87      0.87      0.87       715
   weighted avg       0.87      0.87      0.87       715

ROC-AUC: 0.8736

==================================================
  Decision Tree | external
==================================================
                 precision    recall  f1-score   support

         BENIGN       1.00      0.93      0.96       500
SSTI_Vulnerable       0.55      0.98      0.71        47

       accuracy                           0.93       547
      macro avg       0.78      0.95      0.83       547
   weighted avg       0.96      0.93      0.94       547

ROC-AUC: 0.9600

==================================================
  Random Forest | grouped holdout
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.90      0.87      0.89       331
SSTI_Vulnerable       0.89      0.92      0.91       384

       accuracy                           0.90       715
      macro avg       0.90      0.89      0.90       715
   weighted avg       0.90      0.90      0.90       715

ROC-AUC: 0.9647

==================================================
  Random Forest | external
==================================================
                 precision    recall  f1-score   support

         BENIGN       1.00      0.95      0.97       500
SSTI_Vulnerable       0.63      0.96      0.76        47

       accuracy                           0.95       547
      macro avg       0.81      0.95      0.87       547
   weighted avg       0.96      0.95      0.95       547

ROC-AUC: 0.9865

==================================================
  XGBoost | grouped holdout
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.90      0.85      0.88       331
SSTI_Vulnerable       0.88      0.92      0.90       384

       accuracy                           0.89       715
      macro avg       0.89      0.89      0.89       715
   weighted avg       0.89      0.89      0.89       715

ROC-AUC: 0.9670

==================================================
  XGBoost | external
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.94      0.97       500
SSTI_Vulnerable       0.59      0.94      0.73        47

       accuracy                           0.94       547
      macro avg       0.79      0.94      0.85       547
   weighted avg       0.96      0.94      0.95       547

ROC-AUC: 0.9871

In [11]:
# Comparison table. Read each model left to right:
#   random split -> grouped holdout : how much the random split flattered it
#   external                        : the honest picture (only ~9% attacks,
#                                     so precision drops here first)
order = ["random split (cell 8)", "grouped holdout", "external"]
table = comparison.pivot(index="model", columns="reading",
                         values=["roc_auc", "precision", "recall", "false_alarms"])
table = table.reindex(columns=order, level="reading")
table.round(3)

                                  roc_auc                           \
reading             random split (cell 8) grouped holdout external
model
Decision Tree                       0.918           0.874    0.960
KNN                                 0.952           0.916    0.956
Logistic Regression                 0.958           0.946    0.974
Naive Bayes                         0.932           0.909    0.966
Random Forest                       0.978           0.965    0.987
SVM                                 0.975           0.957    0.981
XGBoost                             0.980           0.967    0.987

                                precision                           \
reading             random split (cell 8) grouped holdout external
model
Decision Tree                       0.909           0.862    0.554
KNN                                 0.935           0.887    0.592
Logistic Regression                 0.907           0.868    0.478
Naive Bayes                         0.973           0.936    0.686
Random Forest                       0.920           0.891    0.634
SVM                                 0.937           0.904    0.614
XGBoost                             0.927           0.880    0.595

                                   recall                           \
reading             random split (cell 8) grouped holdout external
model
Decision Tree                       0.911           0.898    0.979
KNN                                 0.908           0.898    0.894
Logistic Regression                 0.840           0.839    0.915
Naive Bayes                         0.634           0.682    0.745
Random Forest                       0.931           0.919    0.957
SVM                                 0.903           0.880    0.915
XGBoost                             0.931           0.919    0.936

                             false_alarms
reading             random split (cell 8) grouped holdout external
model
Decision Tree                        36.0            55.0     37.0
KNN                                  25.0            44.0     29.0
Logistic Regression                  34.0            49.0     47.0
Naive Bayes                           7.0            18.0     16.0
Random Forest                        32.0            43.0     26.0
SVM                                  24.0            36.0     27.0
XGBoost                              29.0            48.0     30.0

## Experiment: which attack mechanisms get caught?

Every training attack has an automatic `mechanism` label: `probe`, `direct-execution`, `introspection`, `enumeration`, `feature-abuse` or `uncertain`. This experiment asks whether some kinds of attack are easier to catch than others.

Points to keep in mind when reading it:

- The labels were assigned automatically and have **not** been reviewed by a person, so this is error analysis, not a final result.
- Only **recall** can be measured per mechanism. Benign rows have no mechanism, so there is nothing to compute precision against.
- Every attack is tested exactly once, by a model that never saw its skeleton (5 grouped folds), so small mechanisms still get a usable number of test cases.

In [12]:
# ======================================================================
# STEP 8 — RECALL PER ATTACK MECHANISM
# ======================================================================
# Why 5 grouped folds and not the single split from STEP 6: with folds,
# every row is in the holdout exactly once. One split would test only ~20
# probes, where a single miss moves recall by 5 points.
#
# Runtime: a few minutes (2 models x 5 folds, each with its own tuning).

MECHANISM_MODELS = {"XGBoost": train_xgboost, "Random Forest": train_random_forest}

# The mechanism labels live in the combined file, not the features file.
# Both have the same rows in the same order; the assert checks it.
combined = pd.read_csv("../Dataset/train/combined/train_combined.csv", keep_default_na=False)
feature_rows = pd.read_csv(FEATURES_FILE, keep_default_na=False)
assert len(combined) == len(df) and (combined["payload"] == feature_rows["payload"]).all()

X_all = df.drop(columns=["label", "base_id"])
y_all = df["label"]
folds = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

attack_rows = []
for fold, (train_idx, test_idx) in enumerate(folds.split(X_all, y_all, df["base_id"]), start=1):
    x_tr, x_te, _ = scale_payload_length(X_all.iloc[train_idx], X_all.iloc[test_idx])
    y_tr = y_all.iloc[train_idx]
    x_attacks = x_te[y_all.iloc[test_idx].values == 1]     # score the attacks only

    for name, train_fn in MECHANISM_MODELS.items():
        model = train_fn(x_tr, y_tr)
        attack_rows.append(pd.DataFrame({
            "fold": fold,
            "model": name,
            "mechanism": combined.loc[x_attacks.index, "mechanism"].values,
            "payload": combined.loc[x_attacks.index, "payload"].values,
            "score": model.predict_proba(x_attacks)[:, 1],
        }))
    print(f"fold {fold} done")

attack_scores = pd.concat(attack_rows, ignore_index=True)
attack_scores["caught"] = attack_scores["score"] >= 0.5

  best params: {'subsample': 0.8, 'n_estimators': 800, 'max_depth': 4, 'learning_rate': 0.03, 'colsample_bytree': 0.8}

  best params: {'n_estimators': 200, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': 40}
fold 1 done

  best params: {'subsample': 0.8, 'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.03, 'colsample_bytree': 1.0}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
fold 2 done

  best params: {'subsample': 0.8, 'n_estimators': 800, 'max_depth': 4, 'learning_rate': 0.03, 'colsample_bytree': 0.8}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
fold 3 done

  best params: {'subsample': 1.0, 'n_estimators': 300, 'max_depth': 6, 'learning_rate': 0.1, 'colsample_bytree': 1.0}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
fold 4 done

  best params: {'subsample': 0.8, 'n_estimators': 800, 'max_depth': 4, 'learning_rate': 0.03, 'colsample_bytree': 0.8}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
fold 5 done

In [13]:
def recall_interval(caught, total, z=1.96):
    # 95% Wilson interval for a recall. With small groups (about 100 probes)
    # the interval is wide; two mechanisms whose intervals overlap have not
    # been shown to differ.
    p = caught / total
    centre = (p + z**2 / (2 * total)) / (1 + z**2 / total)
    half = z * np.sqrt(p * (1 - p) / total + z**2 / (4 * total**2)) / (1 + z**2 / total)
    return centre - half, centre + half


by_mechanism = (attack_scores
                .groupby(["model", "mechanism"])
                .agg(attacks=("caught", "size"),
                     caught=("caught", "sum"),
                     median_score=("score", "median"))
                .reset_index())
by_mechanism["recall"] = by_mechanism["caught"] / by_mechanism["attacks"]
by_mechanism[["recall_low", "recall_high"]] = [
    recall_interval(c, n) for c, n in zip(by_mechanism["caught"], by_mechanism["attacks"])]

by_mechanism.sort_values(["model", "recall"]).round(3)

,model,mechanism,attacks,caught,median_score,recall,recall_low,recall_high
5,Random Forest,uncertain,630,511,0.898,0.811,0.779,0.840
1,Random Forest,enumeration,107,96,0.854,0.897,0.825,0.942
0,Random Forest,direct-execution,670,650,0.995,0.970,0.954,0.981
2,Random Forest,feature-abuse,130,129,0.972,0.992,0.958,0.999
3,Random Forest,introspection,265,263,0.998,0.992,0.973,0.998
4,Random Forest,probe,103,103,0.953,1.000,0.964,1.000
11,XGBoost,uncertain,630,500,0.925,0.794,0.760,0.823
7,XGBoost,enumeration,107,89,0.891,0.832,0.750,0.891
6,XGBoost,direct-execution,670,646,0.998,0.964,0.947,0.976
8,XGBoost,feature-abuse,130,126,0.975,0.969,0.924,0.988
10,XGBoost,probe,103,101,0.979,0.981,0.932,0.995
9,XGBoost,introspection,265,263,1.000,0.992,0.973,0.998

In [14]:
# What the misses look like: the 3 lowest-scored missed attacks per
# mechanism, for XGBoost. Read these before trusting the table above;
# a "miss" can also be a row that was never a real attack.
missed = attack_scores[(attack_scores["model"] == "XGBoost") & ~attack_scores["caught"]]
missed.sort_values("score").groupby("mechanism").head(3)[["mechanism", "score", "payload"]]

,mechanism,score,payload
3320,uncertain,0.005800,Dus{XXXXXXX}tjs
2250,direct-execution,0.007117,<%= `calc` rescue `open /Applications/Calculat...
2480,uncertain,0.019836,http://vulnerable-website.com/?name={{bad-stuf...
3059,uncertain,0.027130,{include file='php://filter/convert.base64-enc...
3304,feature-abuse,0.043312,{{['nslookup oastify.com']|filter('system')}}
62,direct-execution,0.089799,{insert name='passthru' script='id'}
51,direct-execution,0.092702,{assign var='cmd' value='passthru'}
1731,probe,0.098365,<%= with almost everything before appended unt...
1625,enumeration,0.098369,{{dump(_context)}}
24,enumeration,0.158457,{{request.environ['werkzeug.server.shutdown']()}}
900,enumeration,0.166446,FILENAME{% set var = dump(_context)[OFFSET:LEN...
3089,introspection,0.343452,{{cycler|attr('\x5f\x5finit\x5f\x5f')|attr('\x...
851,feature-abuse,0.346895,{{_self.env.registerUndefinedFilterCallback('s...
3029,feature-abuse,0.383912,{php}echo readfile('flag.txt');{/php}
3377,probe,0.437780,{{1in[1]}}
13,introspection,0.447435,{{get_flashed_messages.__globals__}}

In [15]:
# ======================================================================
# STEP 4 — ORCHESTRATION: run the whole experiment in one call
# ======================================================================

# Registry of every model in the comparison. Adding a new model to the
# study = one train_*() function + one line here. Nothing else changes.
MODEL_TRAINERS = {
    "Naive Bayes":         train_naive_bayes,
    "Logistic Regression": train_logistic_regression,
    "Decision Tree":       train_decision_tree,
    "Random Forest":       train_random_forest,
    "XGBoost":             train_xgboost,
    "KNN":                 train_knn,
    "SVM":                 train_svm,
}

def run_pipeline(preprocess_fn, csv_path, models_to_run=None):
    """
    The full experiment: preprocess -> train all -> evaluate all.

    preprocess_fn: the dataset-specific preprocessing function to use
    (e.g. preprocess_ssti today, preprocess_cicids later). Each dataset
    gets its own function with its own quirks; the pipeline just calls
    whichever one it's handed. It must return, in this order:
        x_train, x_test, y_train, y_test, class_names, scaler

    models_to_run: optional list of names from MODEL_TRAINERS, so you can
    do a quick run with just ["Naive Bayes", "Decision Tree"] while
    iterating on features, then run everything for the final results.

    Returns (models, results_df, scaler) so you can inspect any fitted
    model afterwards (e.g. feature importances, SHAP) and reuse the
    scaler on new data.
    """
    # --- data ---
    # All dataset-specific logic lives inside preprocess_fn; the pipeline
    # only depends on the agreed return order.
    (x_train, x_test, y_train, y_test,
     class_names, scaler) = preprocess_fn(csv_path)

    # --- train ---
    if models_to_run is None:
        models_to_run = list(MODEL_TRAINERS.keys())

    models = {}
    for name in models_to_run:
        print(f"\nTraining {name} ...")
        models[name] = MODEL_TRAINERS[name](x_train, y_train)

    # --- evaluate ---
    results = []
    for name, mdl in models.items():
        results.append(
            evaluate_model(name, mdl, x_test, y_test, class_names)
        )

    # Final comparison table, best model first — this is the headline
    # table for the paper's results section.
    results_df = (pd.DataFrame(results)
                    .sort_values("f1_macro", ascending=False)
                    .reset_index(drop=True))
    print("\n" + "="*50)
    print("  FINAL COMPARISON")
    print("="*50)
    print(results_df.to_string(index=False))

    return models, results_df, scaler