# SSTI detection — model evaluation

## Part 1 — Basic evaluation (random split, threshold 0.5)

Train the 7 models, then test them on the test rows and on the external test set.

In [1]:
"""
Reusable classical-ML modeling pipeline.
========================================

Design goal: point this at ANY tabular dataset with a label column and get
a fair, reproducible comparison of 7 classifiers. Works for binary problems and multiclass problems .

Pipeline shape (always the same order, because order is what protects against data leakage):

    load_data  ->  split_data  ->  scale_features  ->  train  ->  evaluate

Why the order matters:
  - Split BEFORE scaling. The scaler is fitted on training data only, then
    reused to transform the test set. Fitting on the full dataset would leak
    test-set statistics (mean/std) into training — a classic reviewer catch.
  - Stratify the split so rare attack classes appear in both train and test
    at the same ratio as in the full dataset.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import (
    train_test_split, RandomizedSearchCV, StratifiedKFold
)
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    classification_report, confusion_matrix, roc_auc_score, f1_score
)

from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

import warnings
warnings.filterwarnings('ignore')


# ======================================================================
# GLOBAL CONFIG 
# ======================================================================


RANDOM_STATE = 42     # one seed everywhere (split, CV, every model)
TEST_SIZE    = 0.2    # 80/20 train/test split

# Shared CV strategy for every tuned model. StratifiedKFold keeps class proportions identical 
# in each fold — critical when some attack classes are rare. 3 folds instead of 5 because the
# datasets are large and 5 folds nearly doubles tuning time for little gain.
cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)

### Step 1: Data loading and preprocessing

In [2]:
# Load Data 
FEATURES_FILE = 'full_DS_v3.csv'
df = pd.read_csv(FEATURES_FILE)

# Keep the training rows only (the test rows are used in Part 1, Step 3)
df = df[df.split == 'train'].drop(columns=['split'])

# Drop Payload Column
df.drop(columns=['payload',], inplace=True)

#  SPLIT INTO INPUTS (X) AND ANSWER (y)
X = df.drop(columns=['label', 'base_id'])
Y = df.label

# Split Train and Test Data
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state = 15)

# Scale 
scaler = StandardScaler()
x_train["payload_length"] = scaler.fit_transform(x_train[["payload_length"]])
x_test["payload_length"]  = scaler.transform(x_test[["payload_length"]])
# print(x_train[["payload_length"]].head())

### Step 2: Modeling and evaluation

In [3]:


# ======================================================================
# STEP 2 — TRAINING FUNCTIONS (one per model, training ONLY)
# ======================================================================
# Each function does exactly one thing: return a fitted model.

# --- Simple baselines: no tuning needed ------------------------------

def train_naive_bayes(X_train, y_train):
    # GaussianNB has essentially nothing worth tuning. It assumes feature
    # independence, which is false for both network traffic and payload
    # features, so expect it to be the weakest model — its job is to be
    # the floor the other models must beat.
    model = GaussianNB()
    model.fit(X_train, y_train)
    return model


def train_logistic_regression(X_train, y_train):
    # class_weight="balanced" makes mistakes on rare classes cost more,
    # so the model can't win by always predicting the majority class.
    # max_iter raised so the optimizer converges on scaled features.
    model = LogisticRegression(
        max_iter=1000, class_weight="balanced", n_jobs=-1
    )
    model.fit(X_train, y_train)
    return model


# ------------------------------------- Light tuning ------------------------------------- 

def train_decision_tree(X_train, y_train):
    # The params dict is the experiment: these are the knobs being searched.
    params = {
        "max_depth": [None, 10, 20, 40],   # how deep the tree may grow
        "min_samples_leaf": [1, 5, 20],    # bigger leaves = less overfitting
        "criterion": ["gini", "entropy"],  # how splits are scored
    }
    search = RandomizedSearchCV(
        DecisionTreeClassifier(class_weight="balanced",
                               random_state=RANDOM_STATE),
        params,
        n_iter=8,
        scoring="f1_macro",   # macro-F1, not accuracy, so rare classes
                              # count equally — the honest metric for
                              # imbalanced security data
        cv=cv, n_jobs=-1, random_state=RANDOM_STATE
    )
    search.fit(X_train, y_train)
    print("  best params:", search.best_params_)
    return search.best_estimator_


# ------------------------------------- Slow models -----------------------------------------------
# NOTE: on very large datasets (CICIDS2017 full), tune these on a stratified subsample first,
# then refit the best params on all data On the SSTI dataset (~hundreds of rows) they run fine as-is.

def train_svm(X_train, y_train):
    params = {
        "C": [0.1, 1, 10],              # regularization strength
        "gamma": ["scale", 0.01, 0.1],  # reach of one sample's influence
    }
    search = RandomizedSearchCV(
        # probability=True is slower but required: without it SVM can't
        # output probabilities and ROC-AUC (our headline metric) fails.
        SVC(kernel="rbf", probability=True,
            class_weight="balanced", random_state=RANDOM_STATE),
        params, n_iter=6, scoring="f1_macro", cv=cv,
        n_jobs=-1, random_state=RANDOM_STATE
    )
    search.fit(X_train, y_train)
    print("  best params:", search.best_params_)
    return search.best_estimator_


def train_knn(X_train, y_train):
    params = {
        "n_neighbors": [3, 5, 11, 21],       # how many neighbors vote
        "weights": ["uniform", "distance"],  # equal vote vs closer = louder
    }
    search = RandomizedSearchCV(
        KNeighborsClassifier(n_jobs=-1),
        params, n_iter=6, scoring="f1_macro", cv=cv,
        n_jobs=-1, random_state=RANDOM_STATE
    )
    search.fit(X_train, y_train)
    print("  best params:", search.best_params_)
    return search.best_estimator_


# --- Models that genuinely benefit from tuning ------------------------

def train_random_forest(X_train, y_train):
    params = {
        "n_estimators": [200, 400, 600],   # number of trees
        "max_depth": [None, 20, 40],       # depth of each tree
        "min_samples_leaf": [1, 2, 5],     # overfitting control
        "max_features": ["sqrt", "log2"],  # features considered per split
    }
    search = RandomizedSearchCV(
        # "balanced_subsample" recomputes class weights per bootstrap
        # sample — the RF-appropriate version of "balanced".
        RandomForestClassifier(class_weight="balanced_subsample",
                               random_state=RANDOM_STATE, n_jobs=-1),
        params, n_iter=10, scoring="f1_macro", cv=cv,
        n_jobs=-1, random_state=RANDOM_STATE
    )
    search.fit(X_train, y_train)
    print("  best params:", search.best_params_)
    return search.best_estimator_


def train_xgboost(X_train, y_train):
    params = {
        "n_estimators": [300, 500, 800],    # boosting rounds
        "max_depth": [4, 6, 8],             # tree depth
        "learning_rate": [0.03, 0.1, 0.2],  # step size per round
        "subsample": [0.8, 1.0],            # row sampling per tree
        "colsample_bytree": [0.8, 1.0],     # feature sampling per tree
    }

    
    n_classes = len(np.unique(y_train))
    metric = "logloss" if n_classes == 2 else "mlogloss" # here we choose ("logloss") for the binary problem and("mlogloss") for the multiclass problem

    search = RandomizedSearchCV(
        # tree_method="hist" = fast histogram algorithm, matters at
        # CICIDS2017 scale.
        XGBClassifier(tree_method="hist", eval_metric=metric,
                      n_jobs=-1, random_state=RANDOM_STATE),
        params, n_iter=12, scoring="f1_macro", cv=cv,             # training — hyperparameters are chosen by scoring="f1_macro" below. 
        n_jobs=-1, random_state=RANDOM_STATE
    )
    search.fit(X_train, y_train)
    print("  best params:", search.best_params_)
    return search.best_estimator_


# ======================================================================
# STEP 3 — EVALUATION (one function, every model, same rules)
# ======================================================================

def evaluate_model(name, model, X_test, y_test, class_names=None):
    """
    Evaluate one fitted model and return its metrics as a dict.

    Handles binary AND multiclass automatically:
      - Binary: roc_auc_score wants ONLY the positive-class probability, i.e. y_prob[:, 1].
      - Multiclass : it wants the full probability matrix plus multi_class='ovr'.
    Getting this wrong is a silent bug — sklearn raises an error in one
    direction but in the other it can compute a misleading number.

    Returns the metrics (instead of only printing) so a comparison table
    can be built across models — that table becomes the results section of the paper.
    """
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)

    print(f"\n{'='*50}")
    print(f"  {name}")
    print(f"{'='*50}")
    print(classification_report(y_test, y_pred, target_names=class_names))

    n_classes = len(np.unique(y_test))
    if n_classes == 2:
        auc = roc_auc_score(y_test, y_prob[:, 1])
    else:
        auc = roc_auc_score(y_test, y_prob,
                            multi_class="ovr", average="macro")
    print(f"ROC-AUC: {auc:.4f}")

    # Confusion matrix heatmap — labeled with real class names when known.
    ticks = class_names if class_names is not None else "auto"
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=ticks, yticklabels=ticks)
    plt.title(f"Confusion matrix — {name}")
    plt.xlabel("Predicted"); plt.ylabel("Actual")
    plt.tight_layout(); plt.show()

    return {
        "model": name,
        "roc_auc": auc,
        "f1_macro": f1_score(y_test, y_pred, average="macro"),
    }

In [4]:
class_names = ['BENIGN', 'SSTI_Vulnerable']

# Train each model. Each function returns a fitted, ready-to-use model.
models = {
    "Naive Bayes":         train_naive_bayes(x_train, y_train),
    "Logistic Regression": train_logistic_regression(x_train, y_train),
    "KNN":                 train_knn(x_train, y_train),
    "SVM":                 train_svm(x_train, y_train),
    "Decision Tree":       train_decision_tree(x_train, y_train),
    "Random Forest":       train_random_forest(x_train, y_train),
    "XGBoost":             train_xgboost(x_train, y_train),
}

# Evaluate each trained model with the same function, so the comparison is fair.
for name, mdl in models.items():
    evaluate_model(name, mdl, x_test, y_test)

  best params: {'weights': 'distance', 'n_neighbors': 3}

  best params: {'gamma': 0.1, 'C': 10}

  best params: {'min_samples_leaf': 1, 'max_depth': 20, 'criterion': 'entropy'}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}

  best params: {'subsample': 0.8, 'n_estimators': 800, 'max_depth': 6, 'learning_rate': 0.03, 'colsample_bytree': 0.8}

==================================================
  Naive Bayes
==================================================
              precision    recall  f1-score   support

           0       0.74      0.98      0.84       389
           1       0.97      0.66      0.79       393

    accuracy                           0.82       782
   macro avg       0.85      0.82      0.81       782
weighted avg       0.85      0.82      0.81       782

ROC-AUC: 0.9413

==================================================
  Logistic Regression
==================================================
              precision    recall  f1-score   support

           0       0.88      0.88      0.88       389
           1       0.89      0.89      0.89       393

    accuracy                           0.88       782
   macro avg       0.88      0.88      0.88       782
weighted avg       0.88      0.88      0.88       782

ROC-AUC: 0.9664

==================================================
  KNN
==================================================
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       389
           1       0.93      0.93      0.93       393

    accuracy                           0.93       782
   macro avg       0.93      0.93      0.93       782
weighted avg       0.93      0.93      0.93       782

ROC-AUC: 0.9609

==================================================
  SVM
==================================================
              precision    recall  f1-score   support

           0       0.94      0.91      0.92       389
           1       0.91      0.94      0.93       393

    accuracy                           0.92       782
   macro avg       0.92      0.92      0.92       782
weighted avg       0.92      0.92      0.92       782

ROC-AUC: 0.9841

==================================================
  Decision Tree
==================================================
              precision    recall  f1-score   support

           0       0.92      0.92      0.92       389
           1       0.92      0.92      0.92       393

    accuracy                           0.92       782
   macro avg       0.92      0.92      0.92       782
weighted avg       0.92      0.92      0.92       782

ROC-AUC: 0.9291

==================================================
  Random Forest
==================================================
              precision    recall  f1-score   support

           0       0.95      0.93      0.94       389
           1       0.93      0.95      0.94       393

    accuracy                           0.94       782
   macro avg       0.94      0.94      0.94       782
weighted avg       0.94      0.94      0.94       782

ROC-AUC: 0.9854

==================================================
  XGBoost
==================================================
              precision    recall  f1-score   support

           0       0.94      0.92      0.93       389
           1       0.92      0.94      0.93       393

    accuracy                           0.93       782
   macro avg       0.93      0.93      0.93       782
weighted avg       0.93      0.93      0.93       782

ROC-AUC: 0.9857

### Step 3: Test the same 7 models on the external test set

In [5]:


# Load the external test set
# The test rows of the same file
external = pd.read_csv(FEATURES_FILE)
external = external[external.split == 'test'].drop(columns=['split']).reset_index(drop=True)

# Drop Payload Column
external.drop(columns=['payload',], inplace=True)

# SPLIT INTO INPUTS (X) AND ANSWER (y)
x_external = external.drop(columns=['label', 'base_id'])
y_external = external.label

# Scale payload_length with the scaler from cell 5 (transform only, no fit)
x_external["payload_length"] = scaler.transform(x_external[["payload_length"]])

# Evaluate each model
for name, mdl in models.items():
    evaluate_model(name + " (external)", mdl, x_external, y_external, class_names)

==================================================
  Naive Bayes (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.97      0.97      0.97       500
SSTI_Vulnerable       0.73      0.69      0.71        51

       accuracy                           0.95       551
      macro avg       0.85      0.83      0.84       551
   weighted avg       0.95      0.95      0.95       551

ROC-AUC: 0.9687

==================================================
  Logistic Regression (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.91      0.95       500
SSTI_Vulnerable       0.52      0.92      0.67        51

       accuracy                           0.91       551
      macro avg       0.76      0.92      0.81       551
   weighted avg       0.95      0.91      0.92       551

ROC-AUC: 0.9762

==================================================
  KNN (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.98      0.96      0.97       500
SSTI_Vulnerable       0.66      0.84      0.74        51

       accuracy                           0.95       551
      macro avg       0.82      0.90      0.86       551
   weighted avg       0.95      0.95      0.95       551

ROC-AUC: 0.9406

==================================================
  SVM (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.96      0.98       500
SSTI_Vulnerable       0.72      0.94      0.81        51

       accuracy                           0.96       551
      macro avg       0.86      0.95      0.90       551
   weighted avg       0.97      0.96      0.96       551

ROC-AUC: 0.9899

==================================================
  Decision Tree (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.96      0.97       500
SSTI_Vulnerable       0.67      0.88      0.76        51

       accuracy                           0.95       551
      macro avg       0.83      0.92      0.87       551
   weighted avg       0.96      0.95      0.95       551

ROC-AUC: 0.9195

==================================================
  Random Forest (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.96      0.98       500
SSTI_Vulnerable       0.71      0.92      0.80        51

       accuracy                           0.96       551
      macro avg       0.85      0.94      0.89       551
   weighted avg       0.97      0.96      0.96       551

ROC-AUC: 0.9807

==================================================
  XGBoost (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.96      0.97       500
SSTI_Vulnerable       0.68      0.88      0.77        51

       accuracy                           0.95       551
      macro avg       0.83      0.92      0.87       551
   weighted avg       0.96      0.95      0.95       551

ROC-AUC: 0.9845

## Part 2 — Threshold selection

Instead of the default cutoff of 0.5, pick one cutoff per model from the **train set only**, then test it on the test set and on the external test set.

### Step 1: Threshold functions

In [6]:
# ======================================================================
# THRESHOLD FUNCTIONS
# ======================================================================
from sklearn.base import clone
from sklearn.model_selection import cross_val_predict, StratifiedGroupKFold
from sklearn.metrics import precision_score, recall_score

FALSE_ALARM_RATE = 0.05   # the threshold may flag at most 5% of benign training rows


def train_scores(model, X_train, y_train, folds=cv, groups=None):
    # Attack probability for every training row. Each row is scored by a copy
    # of the model that did NOT train on it (cross-validation); otherwise the
    # scores would look too good and the threshold would come out too low.
    # clone() keeps the tuned settings but forgets what the model learned.
    return cross_val_predict(clone(model), X_train, y_train, cv=folds,
                             groups=groups, method="predict_proba")[:, 1]


def find_threshold(scores, y_train, false_alarm_rate=FALSE_ALARM_RATE):
    # The cutoff that only `false_alarm_rate` of the benign rows score above.
    # It uses benign rows only, so it still works on the external set, where
    # attacks are about 9% of rows instead of about 49%.
    benign_scores = scores[y_train.values == 0]
    return np.quantile(benign_scores, 1 - false_alarm_rate)


def evaluate_at_threshold(name, model, X_test, y_test, threshold):
    # Like evaluate_model, but flags an attack at `threshold` instead of 0.5.
    y_prob = model.predict_proba(X_test)[:, 1]
    y_pred = (y_prob >= threshold).astype(int)

    print(f"\n{'='*50}")
    print(f"  {name}  (threshold {threshold:.3f})")
    print(f"{'='*50}")
    print(classification_report(y_test, y_pred, target_names=class_names))

    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    return {
        "model": name,
        "threshold": round(threshold, 3),
        "precision": round(precision_score(y_test, y_pred), 3),
        "recall": round(recall_score(y_test, y_pred), 3),
        "f1": round(f1_score(y_test, y_pred), 3),
        "false_alarms": fp,
        "missed_attacks": fn,
    }

### Step 2: Find the threshold on the train set

In [7]:
# Find one threshold per model, using the TRAIN set only
thresholds = {}
for name, mdl in models.items():
    scores = train_scores(mdl, x_train, y_train)
    thresholds[name] = find_threshold(scores, y_train)
    print(f"{name:20s} threshold = {thresholds[name]:.3f}")

Naive Bayes          threshold = 0.000
Logistic Regression  threshold = 0.697
KNN                  threshold = 0.660

SVM                  threshold = 0.756
Decision Tree        threshold = 1.000

Random Forest        threshold = 0.564

XGBoost              threshold = 0.685

### Step 3: Test the thresholds on the test set

In [8]:
# Test each model on the test set with its own threshold
test_results = []
for name, mdl in models.items():
    test_results.append(evaluate_at_threshold(name + " (test)", mdl, x_test, y_test, thresholds[name]))

pd.DataFrame(test_results)

==================================================
  Naive Bayes (test)  (threshold 0.000)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.77      0.97      0.86       389
SSTI_Vulnerable       0.96      0.72      0.82       393

       accuracy                           0.85       782
      macro avg       0.87      0.85      0.84       782
   weighted avg       0.87      0.85      0.84       782


==================================================
  Logistic Regression (test)  (threshold 0.697)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.82      0.97      0.89       389
SSTI_Vulnerable       0.96      0.79      0.87       393

       accuracy                           0.88       782
      macro avg       0.89      0.88      0.88       782
   weighted avg       0.89      0.88      0.88       782


==================================================
  KNN (test)  (threshold 0.660)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.91      0.94      0.92       389
SSTI_Vulnerable       0.94      0.90      0.92       393

       accuracy                           0.92       782
      macro avg       0.92      0.92      0.92       782
   weighted avg       0.92      0.92      0.92       782


==================================================
  SVM (test)  (threshold 0.756)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.91      0.96      0.94       389
SSTI_Vulnerable       0.96      0.90      0.93       393

       accuracy                           0.93       782
      macro avg       0.94      0.93      0.93       782
   weighted avg       0.94      0.93      0.93       782


==================================================
  Decision Tree (test)  (threshold 1.000)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.91      0.93      0.92       389
SSTI_Vulnerable       0.93      0.90      0.92       393

       accuracy                           0.92       782
      macro avg       0.92      0.92      0.92       782
   weighted avg       0.92      0.92      0.92       782

==================================================
  Random Forest (test)  (threshold 0.564)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.93      0.94      0.94       389
SSTI_Vulnerable       0.94      0.93      0.94       393

       accuracy                           0.94       782
      macro avg       0.94      0.94      0.94       782
   weighted avg       0.94      0.94      0.94       782


==================================================
  XGBoost (test)  (threshold 0.685)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.91      0.94      0.92       389
SSTI_Vulnerable       0.93      0.90      0.92       393

       accuracy                           0.92       782
      macro avg       0.92      0.92      0.92       782
   weighted avg       0.92      0.92      0.92       782

,model,threshold,precision,recall,f1,false_alarms,missed_attacks
0,Naive Bayes (test),0.000,0.963,0.720,0.824,11,110
1,Logistic Regression (test),0.697,0.963,0.794,0.870,12,81
2,KNN (test),0.660,0.942,0.903,0.922,22,38
3,SVM (test),0.756,0.962,0.903,0.932,14,38
4,Decision Tree (test),1.000,0.932,0.903,0.917,26,38
5,Random Forest (test),0.564,0.943,0.934,0.939,22,26
6,XGBoost (test),0.685,0.934,0.903,0.918,25,38

### Step 4: Test the thresholds on the external test set

In [9]:
# Same as Step 3, on the external test set from Part 1
external_results = []
for name, mdl in models.items():
    external_results.append(evaluate_at_threshold(name + " (external)", mdl, x_external, y_external, thresholds[name]))

pd.DataFrame(external_results)

==================================================
  Naive Bayes (external)  (threshold 0.000)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.97      0.96      0.96       500
SSTI_Vulnerable       0.63      0.75      0.68        51

       accuracy                           0.94       551
      macro avg       0.80      0.85      0.82       551
   weighted avg       0.94      0.94      0.94       551


==================================================
  Logistic Regression (external)  (threshold 0.697)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.97      0.95      0.96       500
SSTI_Vulnerable       0.61      0.73      0.66        51

       accuracy                           0.93       551
      macro avg       0.79      0.84      0.81       551
   weighted avg       0.94      0.93      0.93       551


==================================================
  KNN (external)  (threshold 0.660)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.98      0.96      0.97       500
SSTI_Vulnerable       0.69      0.84      0.76        51

       accuracy                           0.95       551
      macro avg       0.84      0.90      0.87       551
   weighted avg       0.96      0.95      0.95       551


==================================================
  SVM (external)  (threshold 0.756)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.98      0.98      0.98       500
SSTI_Vulnerable       0.78      0.82      0.80        51

       accuracy                           0.96       551
      macro avg       0.88      0.90      0.89       551
   weighted avg       0.96      0.96      0.96       551

==================================================
  Decision Tree (external)  (threshold 1.000)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.96      0.97       500
SSTI_Vulnerable       0.68      0.88      0.77        51

       accuracy                           0.95       551
      macro avg       0.83      0.92      0.87       551
   weighted avg       0.96      0.95      0.95       551

==================================================
  Random Forest (external)  (threshold 0.564)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.97      0.98       500
SSTI_Vulnerable       0.74      0.90      0.81        51

       accuracy                           0.96       551
      macro avg       0.87      0.93      0.90       551
   weighted avg       0.97      0.96      0.96       551

==================================================
  XGBoost (external)  (threshold 0.685)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.97      0.98       500
SSTI_Vulnerable       0.78      0.88      0.83        51

       accuracy                           0.97       551
      macro avg       0.88      0.93      0.90       551
   weighted avg       0.97      0.97      0.97       551

,model,threshold,precision,recall,f1,false_alarms,missed_attacks
0,Naive Bayes (external),0.000,0.633,0.745,0.685,22,13
1,Logistic Regression (external),0.697,0.607,0.725,0.661,24,14
2,KNN (external),0.660,0.694,0.843,0.761,19,8
3,SVM (external),0.756,0.778,0.824,0.800,12,9
4,Decision Tree (external),1.000,0.682,0.882,0.769,21,6
5,Random Forest (external),0.564,0.742,0.902,0.814,16,5
6,XGBoost (external),0.685,0.776,0.882,0.826,13,6

### Step 5: Same thresholds with grouped folds

In Step 2 the folds ignore `base_id`, so a training row can be scored by a model that trained on a near-copy of it (`{{7*7}}` scored by a model that saw `{{8*9}}`). That makes the scores look too good and the thresholds too low. Here the folds keep every `base_id` on one side; nothing else changes.

In [10]:
# Same as Step 2, but every base_id (payload skeleton) stays inside one fold
train_groups = df.loc[x_train.index, "base_id"]
grouped_folds = StratifiedGroupKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)

grouped_thresholds = {}
for name, mdl in models.items():
    scores = train_scores(mdl, x_train, y_train, folds=grouped_folds, groups=train_groups)
    grouped_thresholds[name] = find_threshold(scores, y_train)
    print(f"{name:20s} threshold = {grouped_thresholds[name]:.3f}   (Step 2: {thresholds[name]:.3f})")

Naive Bayes          threshold = 0.000   (Step 2: 0.000)

Logistic Regression  threshold = 0.683   (Step 2: 0.697)

KNN                  threshold = 0.715   (Step 2: 0.660)

SVM                  threshold = 0.769   (Step 2: 0.756)

Decision Tree        threshold = 1.000   (Step 2: 1.000)

Random Forest        threshold = 0.627   (Step 2: 0.564)

XGBoost              threshold = 0.754   (Step 2: 0.685)

In [11]:
# Test the grouped thresholds on the external test set, next to Step 4
grouped_external_results = []
for name, mdl in models.items():
    grouped_external_results.append(evaluate_at_threshold(name + " (external, grouped)", mdl, x_external, y_external, grouped_thresholds[name]))

pd.concat([pd.DataFrame(external_results), pd.DataFrame(grouped_external_results)]).sort_values("model")

==================================================
  Naive Bayes (external, grouped)  (threshold 0.000)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.97      0.95      0.96       500
SSTI_Vulnerable       0.62      0.75      0.68        51

       accuracy                           0.93       551
      macro avg       0.80      0.85      0.82       551
   weighted avg       0.94      0.93      0.94       551


==================================================
  Logistic Regression (external, grouped)  (threshold 0.683)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.98      0.94      0.96       500
SSTI_Vulnerable       0.57      0.78      0.66        51

       accuracy                           0.93       551
      macro avg       0.77      0.86      0.81       551
   weighted avg       0.94      0.93      0.93       551


==================================================
  KNN (external, grouped)  (threshold 0.715)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.98      0.97      0.97       500
SSTI_Vulnerable       0.72      0.82      0.77        51

       accuracy                           0.95       551
      macro avg       0.85      0.90      0.87       551
   weighted avg       0.96      0.95      0.96       551


==================================================
  SVM (external, grouped)  (threshold 0.769)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.98      0.98      0.98       500
SSTI_Vulnerable       0.78      0.82      0.80        51

       accuracy                           0.96       551
      macro avg       0.88      0.90      0.89       551
   weighted avg       0.96      0.96      0.96       551


==================================================
  Decision Tree (external, grouped)  (threshold 1.000)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.96      0.97       500
SSTI_Vulnerable       0.68      0.88      0.77        51

       accuracy                           0.95       551
      macro avg       0.83      0.92      0.87       551
   weighted avg       0.96      0.95      0.95       551

==================================================
  Random Forest (external, grouped)  (threshold 0.627)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.97      0.98       500
SSTI_Vulnerable       0.74      0.90      0.81        51

       accuracy                           0.96       551
      macro avg       0.87      0.93      0.90       551
   weighted avg       0.97      0.96      0.96       551


==================================================
  XGBoost (external, grouped)  (threshold 0.754)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.97      0.98       500
SSTI_Vulnerable       0.78      0.88      0.83        51

       accuracy                           0.97       551
      macro avg       0.88      0.93      0.90       551
   weighted avg       0.97      0.97      0.97       551

,model,threshold,precision,recall,f1,false_alarms,missed_attacks
4,Decision Tree (external),1.000,0.682,0.882,0.769,21,6
4,"Decision Tree (external, grouped)",1.000,0.682,0.882,0.769,21,6
2,KNN (external),0.660,0.694,0.843,0.761,19,8
2,"KNN (external, grouped)",0.715,0.724,0.824,0.771,16,9
1,Logistic Regression (external),0.697,0.607,0.725,0.661,24,14
1,"Logistic Regression (external, grouped)",0.683,0.571,0.784,0.661,30,11
0,Naive Bayes (external),0.000,0.633,0.745,0.685,22,13
0,"Naive Bayes (external, grouped)",0.000,0.623,0.745,0.679,23,13
5,Random Forest (external),0.564,0.742,0.902,0.814,16,5
5,"Random Forest (external, grouped)",0.627,0.742,0.902,0.814,16,5
3,SVM (external),0.756,0.778,0.824,0.800,12,9
3,"SVM (external, grouped)",0.769,0.778,0.824,0.800,12,9
6,XGBoost (external),0.685,0.776,0.882,0.826,13,6
6,"XGBoost (external, grouped)",0.754,0.776,0.882,0.826,13,6

## Part 3 — Grouped evaluation (split by base_id)

Same as Part 1, but the train/test split keeps every payload skeleton (`base_id`) on one side. In Part 1, 36% of test rows had a near-copy in training (for example `{{7*7}}` in test and `{{8*9}}` in train, both `{{N*N}}`); here none do.

### Step 1: Grouped split functions

In [12]:
# ======================================================================
# GROUPED SPLIT FUNCTIONS
# ======================================================================
from sklearn.model_selection import GroupShuffleSplit
from sklearn.metrics import precision_score, recall_score


def scale_payload_length(x_train, x_test):
    # Same rule as cell 5: fit the scaler on the train set only,
    # then reuse it on the test set.
    x_train, x_test = x_train.copy(), x_test.copy()
    scaler = StandardScaler()
    x_train["payload_length"] = scaler.fit_transform(x_train[["payload_length"]])
    x_test["payload_length"] = scaler.transform(x_test[["payload_length"]])
    return x_train, x_test, scaler


def group_split(X, y, groups, test_size=TEST_SIZE, seed=RANDOM_STATE):
    # Like train_test_split in cell 5, but every base_id stays on ONE side.
    # test_size is a share of base_ids, so the test set is about 20% of rows.
    splitter = GroupShuffleSplit(n_splits=1, test_size=test_size, random_state=seed)
    train_idx, test_idx = next(splitter.split(X, y, groups))

    # Check: no payload skeleton on both sides
    assert not set(groups.iloc[train_idx]) & set(groups.iloc[test_idx])

    x_train, x_test, scaler = scale_payload_length(X.iloc[train_idx], X.iloc[test_idx])
    return x_train, x_test, y.iloc[train_idx], y.iloc[test_idx], scaler


def summary_row(set_name, name, model, X, y):
    # One row for the comparison table at the end of Part 3 (prints nothing)
    y_pred = model.predict(X)
    tn, fp, fn, tp = confusion_matrix(y, y_pred).ravel()
    return {
        "set": set_name,
        "model": name,
        "roc_auc": roc_auc_score(y, model.predict_proba(X)[:, 1]),
        "precision": precision_score(y, y_pred),
        "recall": recall_score(y, y_pred),
        "f1": f1_score(y, y_pred),
        "false_alarms": fp,
        "missed_attacks": fn,
    }

### Step 2: Split the data by base_id

In [13]:
# Same X and Y as cell 5, but no base_id on both sides
gx_train, gx_test, gy_train, gy_test, g_scaler = group_split(X, Y, groups=df.base_id)
print(f"train: {len(gx_train)} rows, test: {len(gx_test)} rows")

train: 3191 rows, test: 715 rows

### Step 3: Train the 7 models on the grouped train set

In [14]:
# Same training functions as cell 8
grouped_models = {
    "Naive Bayes":         train_naive_bayes(gx_train, gy_train),
    "Logistic Regression": train_logistic_regression(gx_train, gy_train),
    "KNN":                 train_knn(gx_train, gy_train),
    "SVM":                 train_svm(gx_train, gy_train),
    "Decision Tree":       train_decision_tree(gx_train, gy_train),
    "Random Forest":       train_random_forest(gx_train, gy_train),
    "XGBoost":             train_xgboost(gx_train, gy_train),
}

  best params: {'weights': 'distance', 'n_neighbors': 3}

  best params: {'gamma': 0.1, 'C': 10}

  best params: {'min_samples_leaf': 1, 'max_depth': 20, 'criterion': 'entropy'}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}

  best params: {'subsample': 0.8, 'n_estimators': 800, 'max_depth': 6, 'learning_rate': 0.03, 'colsample_bytree': 0.8}

### Step 4: Test on the grouped test set

In [15]:
# Evaluate each model on the grouped test set
grouped_rows = []
for name, mdl in grouped_models.items():
    evaluate_model(name + " (grouped test)", mdl, gx_test, gy_test, class_names)
    grouped_rows.append(summary_row("grouped test", name, mdl, gx_test, gy_test))

==================================================
  Naive Bayes (grouped test)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.72      0.94      0.82       331
SSTI_Vulnerable       0.93      0.69      0.79       384

       accuracy                           0.81       715
      macro avg       0.83      0.82      0.80       715
   weighted avg       0.84      0.81      0.80       715

ROC-AUC: 0.9141

==================================================
  Logistic Regression (grouped test)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.87      0.83      0.85       331
SSTI_Vulnerable       0.86      0.90      0.88       384

       accuracy                           0.87       715
      macro avg       0.87      0.86      0.87       715
   weighted avg       0.87      0.87      0.87       715

ROC-AUC: 0.9522

==================================================
  KNN (grouped test)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.93      0.89      0.91       331
SSTI_Vulnerable       0.90      0.94      0.92       384

       accuracy                           0.91       715
      macro avg       0.92      0.91      0.91       715
   weighted avg       0.92      0.91      0.91       715

ROC-AUC: 0.9341

==================================================
  SVM (grouped test)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.90      0.88      0.89       331
SSTI_Vulnerable       0.90      0.91      0.90       384

       accuracy                           0.90       715
      macro avg       0.90      0.89      0.89       715
   weighted avg       0.90      0.90      0.90       715

ROC-AUC: 0.9696

==================================================
  Decision Tree (grouped test)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.89      0.87      0.88       331
SSTI_Vulnerable       0.89      0.91      0.90       384

       accuracy                           0.89       715
      macro avg       0.89      0.89      0.89       715
   weighted avg       0.89      0.89      0.89       715

ROC-AUC: 0.8958

==================================================
  Random Forest (grouped test)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.95      0.90      0.92       331
SSTI_Vulnerable       0.92      0.96      0.94       384

       accuracy                           0.93       715
      macro avg       0.93      0.93      0.93       715
   weighted avg       0.93      0.93      0.93       715

ROC-AUC: 0.9740

==================================================
  XGBoost (grouped test)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.94      0.87      0.90       331
SSTI_Vulnerable       0.89      0.96      0.92       384

       accuracy                           0.91       715
      macro avg       0.92      0.91      0.91       715
   weighted avg       0.92      0.91      0.91       715

ROC-AUC: 0.9768

### Step 5: Test on the external test set

In [16]:
# Same external set as Part 1, Step 3, but scaled with the grouped train set's scaler
gx_external = external.drop(columns=['label', 'base_id'])
gx_external["payload_length"] = g_scaler.transform(gx_external[["payload_length"]])

# Evaluate each model
for name, mdl in grouped_models.items():
    evaluate_model(name + " (external)", mdl, gx_external, y_external, class_names)
    grouped_rows.append(summary_row("external", name, mdl, gx_external, y_external))

==================================================
  Naive Bayes (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.97      0.97      0.97       500
SSTI_Vulnerable       0.72      0.71      0.71        51

       accuracy                           0.95       551
      macro avg       0.85      0.84      0.84       551
   weighted avg       0.95      0.95      0.95       551

ROC-AUC: 0.9675

==================================================
  Logistic Regression (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.91      0.95       500
SSTI_Vulnerable       0.52      0.90      0.66        51

       accuracy                           0.91       551
      macro avg       0.75      0.91      0.80       551
   weighted avg       0.95      0.91      0.92       551

ROC-AUC: 0.9744

==================================================
  KNN (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.95      0.97       500
SSTI_Vulnerable       0.65      0.86      0.74        51

       accuracy                           0.94       551
      macro avg       0.82      0.91      0.85       551
   weighted avg       0.95      0.94      0.95       551

ROC-AUC: 0.9352

==================================================
  SVM (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.96      0.98       500
SSTI_Vulnerable       0.71      0.94      0.81        51

       accuracy                           0.96       551
      macro avg       0.85      0.95      0.89       551
   weighted avg       0.97      0.96      0.96       551

ROC-AUC: 0.9900

==================================================
  Decision Tree (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.94      0.96       500
SSTI_Vulnerable       0.61      0.88      0.72        51

       accuracy                           0.94       551
      macro avg       0.80      0.91      0.84       551
   weighted avg       0.95      0.94      0.94       551

ROC-AUC: 0.9164

==================================================
  Random Forest (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.96      0.98       500
SSTI_Vulnerable       0.72      0.90      0.80        51

       accuracy                           0.96       551
      macro avg       0.85      0.93      0.89       551
   weighted avg       0.96      0.96      0.96       551

ROC-AUC: 0.9809

==================================================
  XGBoost (external)
==================================================
                 precision    recall  f1-score   support

         BENIGN       0.99      0.96      0.97       500
SSTI_Vulnerable       0.68      0.88      0.77        51

       accuracy                           0.95       551
      macro avg       0.83      0.92      0.87       551
   weighted avg       0.96      0.95      0.95       551

ROC-AUC: 0.9840

### Step 6: Compare Part 1 with Part 3

In [17]:
# Add the Part 1 models on the random-split test set, then compare.
# Read each model left to right:
#   random split -> grouped test : how much the random split flattered it
#   external                     : data from a different source, only ~9% attacks
for name, mdl in models.items():
    grouped_rows.append(summary_row("random split (Part 1)", name, mdl, x_test, y_test))

comparison = pd.DataFrame(grouped_rows)
table = comparison.pivot(index="model", columns="set",
                         values=["roc_auc", "precision", "recall", "false_alarms"])
table.reindex(columns=["random split (Part 1)", "grouped test", "external"], level="set").round(3)

                                  roc_auc                        \
set                 random split (Part 1) grouped test external
model
Decision Tree                       0.929        0.896    0.916
KNN                                 0.961        0.934    0.935
Logistic Regression                 0.966        0.952    0.974
Naive Bayes                         0.941        0.914    0.967
Random Forest                       0.985        0.974    0.981
SVM                                 0.984        0.970    0.990
XGBoost                             0.986        0.977    0.984

                                precision                        \
set                 random split (Part 1) grouped test external
model
Decision Tree                       0.921        0.891    0.608
KNN                                 0.931        0.905    0.647
Logistic Regression                 0.885        0.862    0.517
Naive Bayes                         0.967        0.933    0.720
Random Forest                       0.928        0.915    0.719
SVM                                 0.913        0.895    0.706
XGBoost                             0.920        0.893    0.682

                                   recall                        \
set                 random split (Part 1) grouped test external
model
Decision Tree                       0.921        0.911    0.882
KNN                                 0.926        0.940    0.863
Logistic Regression                 0.885        0.896    0.902
Naive Bayes                         0.662        0.688    0.706
Random Forest                       0.949        0.956    0.902
SVM                                 0.939        0.911    0.941
XGBoost                             0.941        0.956    0.882

                             false_alarms
set                 random split (Part 1) grouped test external
model
Decision Tree                        31.0         43.0     29.0
KNN                                  27.0         38.0     24.0
Logistic Regression                  45.0         55.0     43.0
Naive Bayes                           9.0         19.0     14.0
Random Forest                        29.0         34.0     18.0
SVM                                  35.0         41.0     20.0
XGBoost                              32.0         44.0     21.0

## Part 4 — Which attack mechanisms get caught?

Every training attack has an automatic `mechanism` label: `probe`, `direct-execution`, `introspection`, `enumeration`, `feature-abuse` or `uncertain`. This part measures how many attacks of each kind XGBoost and Random Forest catch, first with random folds and then with folds split by `base_id`.

- The labels were assigned automatically and are **not** reviewed by a person.
- Only **recall** can be measured per mechanism: benign rows have no mechanism, so there is nothing to compute precision against.
- 5 folds, so every attack is tested exactly once by a model that did not train on it.

### Step 1: Mechanism functions

In [18]:
# ======================================================================
# MECHANISM FUNCTIONS
# ======================================================================
MECHANISM_MODELS = {"XGBoost": train_xgboost, "Random Forest": train_random_forest}

# Load the mechanism label of every training row.
# train_combined.csv has the same rows in the same order as the features file.
combined = pd.read_csv("../Dataset/train/combined/train_combined.csv", keep_default_na=False)
features_check = pd.read_csv(FEATURES_FILE, keep_default_na=False)
features_check = features_check[features_check.split == "train"]   # training rows only
assert (combined["payload"] == features_check["payload"]).all()   # same rows, same order

mechanism = combined["mechanism"]
payload_text = combined["payload"]


def mechanism_scores(folds, groups=None):
    # Train on 4/5 of the data and score the attacks in the other 1/5, five times.
    # At the end every attack has been scored once, by a model that did not train on it.
    rows = []
    for fold, (train_idx, test_idx) in enumerate(folds.split(X, Y, groups), start=1):
        x_tr, x_te, _ = scale_payload_length(X.iloc[train_idx], X.iloc[test_idx])
        y_tr = Y.iloc[train_idx]
        x_attacks = x_te[Y.iloc[test_idx] == 1]     # attacks only: benign rows have no mechanism

        for name, train_fn in MECHANISM_MODELS.items():
            model = train_fn(x_tr, y_tr)
            rows.append(pd.DataFrame({
                "model": name,
                "mechanism": mechanism[x_attacks.index].values,
                "payload": payload_text[x_attacks.index].values,
                "score": model.predict_proba(x_attacks)[:, 1],
            }))
        print(f"fold {fold} done")

    scores = pd.concat(rows, ignore_index=True)
    scores["caught"] = scores["score"] >= 0.5
    return scores


def recall_interval(caught, total, z=1.96):
    # 95% range for a recall (Wilson interval). If two mechanisms' ranges
    # overlap, the difference between them is not proven.
    p = caught / total
    centre = (p + z**2 / (2 * total)) / (1 + z**2 / total)
    half = z * np.sqrt(p * (1 - p) / total + z**2 / (4 * total**2)) / (1 + z**2 / total)
    return centre - half, centre + half


def mechanism_table(scores):
    # One row per model and mechanism: attacks, caught, recall and its 95% range
    table = (scores.groupby(["model", "mechanism"])
                   .agg(attacks=("caught", "size"), caught=("caught", "sum"))
                   .reset_index())
    table["recall"] = table["caught"] / table["attacks"]
    table[["recall_low", "recall_high"]] = [
        recall_interval(c, n) for c, n in zip(table["caught"], table["attacks"])]
    return table.sort_values(["model", "recall"])

### Step 2: Recall per mechanism with random folds (no grouping)

In [19]:
# Random folds, like the split in Part 1: near-copies can be on both sides
random_folds = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

random_scores = mechanism_scores(random_folds)
random_table = mechanism_table(random_scores)
random_table.round(3)

  best params: {'subsample': 0.8, 'n_estimators': 800, 'max_depth': 4, 'learning_rate': 0.03, 'colsample_bytree': 0.8}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
fold 1 done

  best params: {'subsample': 0.8, 'n_estimators': 800, 'max_depth': 4, 'learning_rate': 0.03, 'colsample_bytree': 0.8}

  best params: {'n_estimators': 400, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': 40}
fold 2 done

  best params: {'subsample': 0.8, 'n_estimators': 800, 'max_depth': 6, 'learning_rate': 0.03, 'colsample_bytree': 0.8}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
fold 3 done

  best params: {'subsample': 0.8, 'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.03, 'colsample_bytree': 1.0}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
fold 4 done

  best params: {'subsample': 0.8, 'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.03, 'colsample_bytree': 1.0}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
fold 5 done

,model,mechanism,attacks,caught,recall,recall_low,recall_high
5,Random Forest,uncertain,630,553,0.878,0.850,0.901
1,Random Forest,enumeration,107,94,0.879,0.803,0.928
4,Random Forest,probe,103,100,0.971,0.918,0.990
2,Random Forest,feature-abuse,130,128,0.985,0.946,0.996
0,Random Forest,direct-execution,670,662,0.988,0.977,0.994
3,Random Forest,introspection,265,263,0.992,0.973,0.998
7,XGBoost,enumeration,107,93,0.869,0.792,0.920
11,XGBoost,uncertain,630,550,0.873,0.845,0.897
10,XGBoost,probe,103,100,0.971,0.918,0.990
8,XGBoost,feature-abuse,130,128,0.985,0.946,0.996
6,XGBoost,direct-execution,670,660,0.985,0.973,0.992
9,XGBoost,introspection,265,265,1.000,0.986,1.000

### Step 3: Recall per mechanism with grouped folds

In [20]:
# Grouped folds, like the split in Part 3: no base_id on both sides
grouped_folds = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

grouped_scores = mechanism_scores(grouped_folds, groups=df.base_id)
grouped_table = mechanism_table(grouped_scores)
grouped_table.round(3)

  best params: {'subsample': 1.0, 'n_estimators': 800, 'max_depth': 6, 'learning_rate': 0.03, 'colsample_bytree': 0.8}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
fold 1 done

  best params: {'subsample': 1.0, 'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.03, 'colsample_bytree': 1.0}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
fold 2 done

  best params: {'subsample': 1.0, 'n_estimators': 300, 'max_depth': 6, 'learning_rate': 0.1, 'colsample_bytree': 1.0}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
fold 3 done

  best params: {'subsample': 0.8, 'n_estimators': 800, 'max_depth': 6, 'learning_rate': 0.03, 'colsample_bytree': 0.8}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
fold 4 done

  best params: {'subsample': 0.8, 'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.03, 'colsample_bytree': 1.0}

  best params: {'n_estimators': 400, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 20}
fold 5 done

,model,mechanism,attacks,caught,recall,recall_low,recall_high
5,Random Forest,uncertain,630,545,0.865,0.836,0.890
1,Random Forest,enumeration,107,94,0.879,0.803,0.928
4,Random Forest,probe,103,100,0.971,0.918,0.990
2,Random Forest,feature-abuse,130,128,0.985,0.946,0.996
0,Random Forest,direct-execution,670,661,0.987,0.975,0.993
3,Random Forest,introspection,265,263,0.992,0.973,0.998
11,XGBoost,uncertain,630,536,0.851,0.821,0.876
7,XGBoost,enumeration,107,92,0.860,0.782,0.913
10,XGBoost,probe,103,100,0.971,0.918,0.990
6,XGBoost,direct-execution,670,659,0.984,0.971,0.991
8,XGBoost,feature-abuse,130,128,0.985,0.946,0.996
9,XGBoost,introspection,265,263,0.992,0.973,0.998

### Step 4: Compare random and grouped folds

In [21]:
# gap = random recall - grouped recall
# A large gap means part of that mechanism's recall came from near-copies.
compare = pd.concat([random_table.assign(folds="random"), grouped_table.assign(folds="grouped")])
compare = compare.pivot_table(index=["model", "mechanism"], columns="folds", values="recall")[["random", "grouped"]]
compare["gap"] = compare["random"] - compare["grouped"]
compare.sort_values("gap", ascending=False).round(3)

folds                           random  grouped    gap
model         mechanism
XGBoost       uncertain          0.873    0.851  0.022
Random Forest uncertain          0.878    0.865  0.013
XGBoost       enumeration        0.869    0.860  0.009
              introspection      1.000    0.992  0.008
              direct-execution   0.985    0.984  0.001
Random Forest direct-execution   0.988    0.987  0.001
              enumeration        0.879    0.879  0.000
              feature-abuse      0.985    0.985  0.000
              introspection      0.992    0.992  0.000
              probe              0.971    0.971  0.000
XGBoost       feature-abuse      0.985    0.985  0.000
              probe              0.971    0.971  0.000

### Step 5: Look at the missed attacks

In [22]:
# The 3 lowest-scored missed attacks per mechanism (XGBoost, grouped folds).
# Read these before trusting the tables: a "miss" can be a row that was never a real attack.
missed = grouped_scores[(grouped_scores["model"] == "XGBoost") & ~grouped_scores["caught"]]
missed.sort_values("score").groupby("mechanism").head(3)[["mechanism", "score", "payload"]]

,mechanism,score,payload
2250,direct-execution,0.005800,<%= `calc` rescue `open /Applications/Calculat...
3320,uncertain,0.009340,Dus{XXXXXXX}tjs
870,uncertain,0.009822,{% block body %}
921,uncertain,0.011541,{% import foobar %} = Error
900,enumeration,0.017512,FILENAME{% set var = dump(_context)[OFFSET:LEN...
3304,feature-abuse,0.040907,{{['nslookup oastify.com']|filter('system')}}
1731,probe,0.048162,<%= with almost everything before appended unt...
24,enumeration,0.083024,{{request.environ['werkzeug.server.shutdown']()}}
898,feature-abuse,0.134279,"{% for a in [""error_reporting"", ""1""]|sort(""ini..."
193,direct-execution,0.139992,<%=(`nslookup oastify.com`)%>
901,direct-execution,0.173313,"{{id~passthru~_context|join|slice(2,2)|split(0..."
1625,enumeration,0.197376,{{dump(_context)}}
3089,introspection,0.369989,{{cycler|attr('\x5f\x5finit\x5f\x5f')|attr('\x...
2508,introspection,0.376820,"{% for key, value in config.items() %}"
3368,probe,0.434395,"38/52 error, 2/52 modified, length 13. It beha..."
222,probe,0.447546,"{{ 1 / ([""id >>/dev/null && echo -n 1"", ""0""]|s..."

In [23]:
# ======================================================================
# STEP 4 — ORCHESTRATION: run the whole experiment in one call
# ======================================================================

# Registry of every model in the comparison. Adding a new model to the
# study = one train_*() function + one line here. Nothing else changes.
MODEL_TRAINERS = {
    "Naive Bayes":         train_naive_bayes,
    "Logistic Regression": train_logistic_regression,
    "Decision Tree":       train_decision_tree,
    "Random Forest":       train_random_forest,
    "XGBoost":             train_xgboost,
    "KNN":                 train_knn,
    "SVM":                 train_svm,
}

def run_pipeline(preprocess_fn, csv_path, models_to_run=None):
    """
    The full experiment: preprocess -> train all -> evaluate all.

    preprocess_fn: the dataset-specific preprocessing function to use
    (e.g. preprocess_ssti today, preprocess_cicids later). Each dataset
    gets its own function with its own quirks; the pipeline just calls
    whichever one it's handed. It must return, in this order:
        x_train, x_test, y_train, y_test, class_names, scaler

    models_to_run: optional list of names from MODEL_TRAINERS, so you can
    do a quick run with just ["Naive Bayes", "Decision Tree"] while
    iterating on features, then run everything for the final results.

    Returns (models, results_df, scaler) so you can inspect any fitted
    model afterwards (e.g. feature importances, SHAP) and reuse the
    scaler on new data.
    """
    # --- data ---
    # All dataset-specific logic lives inside preprocess_fn; the pipeline
    # only depends on the agreed return order.
    (x_train, x_test, y_train, y_test,
     class_names, scaler) = preprocess_fn(csv_path)

    # --- train ---
    if models_to_run is None:
        models_to_run = list(MODEL_TRAINERS.keys())

    models = {}
    for name in models_to_run:
        print(f"\nTraining {name} ...")
        models[name] = MODEL_TRAINERS[name](x_train, y_train)

    # --- evaluate ---
    results = []
    for name, mdl in models.items():
        results.append(
            evaluate_model(name, mdl, x_test, y_test, class_names)
        )

    # Final comparison table, best model first — this is the headline
    # table for the paper's results section.
    results_df = (pd.DataFrame(results)
                    .sort_values("f1_macro", ascending=False)
                    .reset_index(drop=True))
    print("\n" + "="*50)
    print("  FINAL COMPARISON")
    print("="*50)
    print(results_df.to_string(index=False))

    return models, results_df, scaler